--- !ruby/object:Trainer
my_pokemon:
  0: !ruby/object:Pokemon
    name: Bulbasaur
    type: Grass
    level: 3
    learnset:
      Tackle: 0
      Growl: 3
      Leech Seed: 7
      Vine Whip: 9
      Poison Powder: 13
      Sleep Powder: 13
      Take Down: 15
      Razor Leaf: 19
      Sweet Scent: 21
      Growth: 25
      Double-Edge: 27
      Worry Seed: 31
      Synthesis: 33
      Seed Bomb: 37
    moves:
    - Tackle
    - Growl
    hp: 45
    attack: 49
    defense: 49
    sp_atk: 65
    sp_def: 65
    speed: 45
  1: !ruby/object:Pokemon
    name: Beheeyem
    type: Psychic
    level: 3
    learnset:
      Confusion: 0
      Growl: 4
      Heal Block: 8
      Miracle Eye: 11
      Psybeam: 15
      Headbutt: 18
      Hidden Power: 22
      Imprison: 25
      Simple Beam: 29
      Zen Headbutt: 32
      Psych Up: 36
      Psychic: 39
      Calm Mind: 45
      Recover: 50
      Guard Split: 56
      Power Split: 58
      Synchronoise: 63
      Wonder Room: 68
    moves:
    - Confusion
    hp: 75
    attack: 75
    defense: 75
    sp_atk: 125
    sp_def: 95
    speed: 40
  2: !ruby/object:Pokemon
    name: Lickilicky
    type: Normal
    level: 3
    learnset:
      Lick: 0
      Supersonic: 5
      Defense Curl: 9
      Knock Off: 13
      Wrap: 17
      Stomp: 21
      Disable: 25
      Slam: 29
      Rollout: 33
      Chip Away: 37
      Me First: 41
      Refresh: 45
      Screech: 49
      Power Whip: 53
      Wring Out: 57
      Gyro Ball: 61
    moves:
    - Lick
    hp: 110
    attack: 85
    defense: 95
    sp_atk: 80
    sp_def: 95
    speed: 50
  3: !ruby/object:Pokemon
    name: Electrike
    type: Electric
    level: 3
    learnset:
      Tackle: 0
      Thunder Wave: 4
      Leer: 9
      Howl: 12
      Quick Attack: 17
      Spark: 20
      Odor Sleuth: 25
      Bite: 28
      Thunder Fang: 33
      Roar: 36
      Discharge: 41
      Charge: 44
      Wild Charge: 49
      Thunder: 52
    moves:
    - Tackle
    hp: 40
    attack: 45
    defense: 40
    sp_atk: 65
    sp_def: 40
    speed: 65
  4: !ruby/object:Pokemon
    name: Beartic
    type: Ice
    level: 3
    learnset:
      Superpower: 0
      Aqua Jet: 0
      Powder Snow: 0
      Growl: 5
      Bide: 9
      Icy Wind: 13
      Fury Swipes: 17
      Brine: 21
      Endure: 25
      Swagger: 29
      Slash: 33
      Flail: 36
      Icicle Crash: 37
      Rest: 41
      Blizzard: 45
      Hail: 53
      Thrash: 59
      Sheer Cold: 66
    moves:
    - Superpower
    - Aqua Jet
    - Powder Snow
    hp: 95
    attack: 110
    defense: 80
    sp_atk: 70
    sp_def: 80
    speed: 50
  5: !ruby/object:Pokemon
    name: Klink
    type: Steel
    level: 3
    learnset:
      Vice Grip: 0
      Charge: 6
      ThunderShock: 11
      Gear Grind: 16
      Bind: 21
      Charge Beam: 26
      Autotomize: 31
      Mirror Shot: 36
      Screech: 39
      Discharge: 42
      Metal Sound: 45
      Shift Gear: 48
      Lock-On: 51
      Zap Cannon: 54
      Hyper Beam: 57
    moves:
    - Vice Grip
    hp: 40
    attack: 55
    defense: 70
    sp_atk: 45
    sp_def: 60
    speed: 30
name: Nikki
