--- !ruby/object:Trainer
my_pokemon:
  0: !ruby/object:Pokemon
    name: Bulbasaur
    type: Grass
    level: 3
    learnset:
      Tackle: 0
      Growl: 3
      Leech Seed: 7
      Vine Whip: 9
      Poison Powder: 13
      Sleep Powder: 13
      Take Down: 15
      Razor Leaf: 19
      Sweet Scent: 21
      Growth: 25
      Double-Edge: 27
      Worry Seed: 31
      Synthesis: 33
      Seed Bomb: 37
    moves:
    - Tackle
    - Growl
    hp: 45
    attack: 49
    defense: 49
    sp_atk: 65
    sp_def: 65
    speed: 45
  1: !ruby/object:Pokemon
    name: Roggenrola
    type: Rock
    level: 3
    learnset:
      Tackle: 0
      Harden: 4
      Sand-Attack: 7
      Headbutt: 10
      Rock Blast: 14
      Mud-Slap: 17
      Iron Defense: 20
      Smack Down: 23
      Rock Slide: 27
      Stealth Rock: 30
      Sandstorm: 33
      Stone Edge: 36
      Explosion: 40
    moves:
    - Tackle
    hp: 55
    attack: 75
    defense: 85
    sp_atk: 25
    sp_def: 25
    speed: 15
  2: !ruby/object:Pokemon
    name: Cubone
    type: Ground
    level: 3
    learnset:
      Growl: 0
      Tail Whip: 3
      Bone Club: 7
      Headbutt: 11
      Leer: 13
      Focus Energy: 17
      Bonemerang: 21
      Rage: 23
      False Swipe: 27
      Thrash: 31
      Fling: 33
      Bone Rush: 37
      Endeavor: 41
      Double-Edge: 43
      Retaliate: 47
    moves:
    - Growl
    - Tail Whip
    hp: 50
    attack: 50
    defense: 95
    sp_atk: 40
    sp_def: 50
    speed: 35
  3: !ruby/object:Pokemon
    name: Castform
    type: Normal
    level: 3
    learnset:
      Tackle: 0
      Water Gun: 10
      Ember: 10
      Powder Snow: 10
      Headbutt: 20
      Rain Dance: 30
      Sunny Day: 30
      Hail: 30
      Weather Ball: 40
      Hydro Pump: 50
      Fire Blast: 50
      Blizzard: 50
    moves:
    - Tackle
    hp: 70
    attack: 70
    defense: 70
    sp_atk: 70
    sp_def: 70
    speed: 70
  4: !ruby/object:Pokemon
    name: Parasect
    type: Bug
    level: 3
    learnset:
      Cross Poison: 0
      Scratch: 0
      Stun Spore: 6
      PoisonPowder: 6
      Leech Life: 11
      Fury Cutter: 17
      Spore: 22
      Slash: 29
      Growth: 37
      Giga Drain: 44
      Aromatherapy: 51
      Rage Powder: 59
      X-Scissor: 66
    moves:
    - Cross Poison
    - Scratch
    hp: 60
    attack: 95
    defense: 80
    sp_atk: 60
    sp_def: 80
    speed: 30
  5: !ruby/object:Pokemon
    name: Kyurem
    type: Dragon
    level: 3
    learnset:
      Icy Wind: 0
      Dragon Rage: 0
      Imprison: 0
      AncientPower: 0
      Ice Beam: 0
      DragonBreath: 0
      Slash: 0
      Scary Face: 43
      Glaciate: 50
      Dragon Pulse: 0
      Endeavor: 0
      Blizzard: 0
      Outrage: 0
      Hyper Voice: 0
      Fusion Bolt: 0
      Freeze Shock: 0
      Fusion Flare: 0
      Ice Burn: 0
    moves:
    - Icy Wind
    - Dragon Rage
    - Imprison
    - AncientPower
    - Ice Beam
    - DragonBreath
    - Slash
    - Dragon Pulse
    - Endeavor
    - Blizzard
    - Outrage
    - Hyper Voice
    - Fusion Bolt
    - Freeze Shock
    - Fusion Flare
    - Ice Burn
    hp: 95
    attack: 700
    defense: 125
    sp_atk: 120
    sp_def: 90
    speed: 170
name: Nikki
